import type {
  Acquisition,
  Alert,
  Clinic,
  DashboardMetrics,
  LicenseRecord,
  Organization,
} from "./types";
import { daysUntil } from "./utils";

export const organization: Organization = {
  name: "Demo Vet Partners",
  locationCount: 127,
  statesActive: 18,
  acquisitionsYtd: 4,
};

export const metrics: DashboardMetrics = {
  compliantLocations: 98,
  atRiskLocations: 21,
  expiredItems: 8,
  renewalsDue30Days: 34,
  acquisitionsInPipeline: 3,
  avgIntegrationDays: 47,
};

export const clinics: Clinic[] = [
  {
    id: "cln-001",
    name: "Northside Animal Hospital",
    city: "Austin",
    state: "TX",
    acquiredAt: "2024-03-12",
    deaNumber: "FA1234567",
    deaExpires: "2026-04-15",
    deaStatus: "at_risk",
    stateLicenseExpires: "2026-06-30",
    stateLicenseStatus: "compliant",
    csLogStatus: "compliant",
    lastAudit: "2025-11-02",
    integrationStatus: "complete",
  },
  {
    id: "cln-002",
    name: "Paws & Claws Veterinary",
    city: "Denver",
    state: "CO",
    acquiredAt: "2025-01-08",
    deaNumber: "FB2345678",
    deaExpires: "2025-12-01",
    deaStatus: "expired",
    stateLicenseExpires: "2026-02-28",
    stateLicenseStatus: "at_risk",
    csLogStatus: "at_risk",
    lastAudit: "2024-08-14",
    integrationStatus: "in_progress",
  },
  {
    id: "cln-003",
    name: "Lakeview Pet Care",
    city: "Chicago",
    state: "IL",
    acquiredAt: "2023-09-20",
    deaNumber: "FC3456789",
    deaExpires: "2027-01-10",
    deaStatus: "compliant",
    stateLicenseExpires: "2027-01-10",
    stateLicenseStatus: "compliant",
    csLogStatus: "compliant",
    lastAudit: "2026-01-15",
    integrationStatus: "complete",
  },
  {
    id: "cln-004",
    name: "Sunrise Veterinary Clinic",
    city: "Phoenix",
    state: "AZ",
    acquiredAt: "2025-11-01",
    deaNumber: "FD4567890",
    deaExpires: "2026-08-22",
    deaStatus: "pending",
    stateLicenseExpires: "2026-05-01",
    stateLicenseStatus: "pending",
    csLogStatus: "pending",
    lastAudit: "—",
    integrationStatus: "not_started",
  },
  {
    id: "cln-005",
    name: "Heritage Animal Clinic",
    city: "Nashville",
    state: "TN",
    acquiredAt: "2024-07-04",
    deaNumber: "FE5678901",
    deaExpires: "2026-03-28",
    deaStatus: "at_risk",
    stateLicenseExpires: "2026-04-01",
    stateLicenseStatus: "at_risk",
    csLogStatus: "compliant",
    lastAudit: "2025-09-30",
    integrationStatus: "complete",
  },
  {
    id: "cln-006",
    name: "Coastal Pet Hospital",
    city: "Tampa",
    state: "FL",
    acquiredAt: "2022-11-15",
    deaNumber: "FF6789012",
    deaExpires: "2026-11-15",
    deaStatus: "compliant",
    stateLicenseExpires: "2026-11-15",
    stateLicenseStatus: "compliant",
    csLogStatus: "compliant",
    lastAudit: "2026-02-01",
    integrationStatus: "complete",
  },
  {
    id: "cln-007",
    name: "Midwest Animal Care",
    city: "Columbus",
    state: "OH",
    acquiredAt: "2025-06-18",
    deaNumber: "FG7890123",
    deaExpires: "2026-02-10",
    deaStatus: "expired",
    stateLicenseExpires: "2026-07-20",
    stateLicenseStatus: "compliant",
    csLogStatus: "at_risk",
    lastAudit: "2025-04-22",
    integrationStatus: "in_progress",
  },
  {
    id: "cln-008",
    name: "Valley Veterinary Group",
    city: "Sacramento",
    state: "CA",
    acquiredAt: "2024-01-22",
    deaNumber: "FH8901234",
    deaExpires: "2026-09-05",
    deaStatus: "compliant",
    stateLicenseExpires: "2026-03-15",
    stateLicenseStatus: "at_risk",
    csLogStatus: "compliant",
    lastAudit: "2025-12-10",
    integrationStatus: "complete",
  },
];

export const acquisitions: Acquisition[] = [
  {
    id: "acq-001",
    targetName: "Blue Ridge Veterinary (6 clinics)",
    locations: 6,
    states: ["NC", "SC"],
    stage: "diligence",
    closeDate: "2026-05-15",
    riskScore: 72,
    flags: [
      {
        id: "f1",
        severity: "critical",
        title: "2 expired DEA registrations found",
        detail: "Asheville and Greenville locations have DEA registrations expired 4+ months.",
      },
      {
        id: "f2",
        severity: "warning",
        title: "Incomplete controlled substance logs",
        detail: "3 of 6 clinics missing biennial inventory records required by DEA.",
      },
    ],
    checklist: [
      {
        id: "c1",
        label: "Pull DEA registrations for all locations",
        owner: "K. Farrell",
        dueDate: "2026-03-20",
        done: true,
      },
      {
        id: "c2",
        label: "Verify state board licenses per clinic",
        owner: "D. DeAngelo",
        dueDate: "2026-03-25",
        done: true,
      },
      {
        id: "c3",
        label: "Audit controlled substance log completeness",
        owner: "D. DeAngelo",
        dueDate: "2026-04-01",
        done: false,
      },
      {
        id: "c4",
        label: "Draft license transfer timeline",
        owner: "Integration team",
        dueDate: "2026-04-10",
        done: false,
      },
    ],
  },
  {
    id: "acq-002",
    targetName: "Prairie Pet Partners (3 clinics)",
    locations: 3,
    states: ["NE", "IA"],
    stage: "integration",
    closeDate: "2026-02-28",
    riskScore: 38,
    flags: [
      {
        id: "f3",
        severity: "warning",
        title: "State license transfer pending",
        detail: "Iowa location awaiting board approval — est. 3 weeks.",
      },
    ],
    checklist: [
      {
        id: "c5",
        label: "File DEA address change notifications",
        owner: "Compliance",
        dueDate: "2026-03-10",
        done: true,
      },
      {
        id: "c6",
        label: "Migrate CS logs to platform template",
        owner: "Field integration",
        dueDate: "2026-03-18",
        done: false,
      },
      {
        id: "c7",
        label: "Schedule post-close compliance audit",
        owner: "Regional ops",
        dueDate: "2026-04-15",
        done: false,
      },
    ],
  },
  {
    id: "acq-003",
    targetName: "Pacific Coast Vets (4 clinics)",
    locations: 4,
    states: ["OR", "WA"],
    stage: "loi",
    closeDate: "2026-07-01",
    riskScore: 55,
    flags: [
      {
        id: "f4",
        severity: "info",
        title: "LOI signed — diligence not started",
        detail: "Compliance review scheduled to begin after data room access.",
      },
    ],
    checklist: [
      {
        id: "c8",
        label: "Request DEA/license documentation from seller",
        owner: "M&A",
        dueDate: "2026-03-30",
        done: false,
      },
      {
        id: "c9",
        label: "Assign integration lead",
        owner: "Ops",
        dueDate: "2026-04-05",
        done: false,
      },
    ],
  },
];

function buildLicenseRecords(): LicenseRecord[] {
  const records: LicenseRecord[] = [];

  for (const clinic of clinics) {
    records.push({
      id: `${clinic.id}-dea`,
      clinicId: clinic.id,
      clinicName: clinic.name,
      type: "dea_registration",
      identifier: clinic.deaNumber,
      state: clinic.state,
      expires: clinic.deaExpires,
      status: clinic.deaStatus,
      daysUntilExpiry: daysUntil(clinic.deaExpires),
    });
    records.push({
      id: `${clinic.id}-state`,
      clinicId: clinic.id,
      clinicName: clinic.name,
      type: "state_vet_license",
      identifier: `${clinic.state}-VET-${clinic.id.slice(-3)}`,
      state: clinic.state,
      expires: clinic.stateLicenseExpires,
      status: clinic.stateLicenseStatus,
      daysUntilExpiry: daysUntil(clinic.stateLicenseExpires),
    });
  }

  return records.sort((a, b) => a.daysUntilExpiry - b.daysUntilExpiry);
}

export const licenseRecords = buildLicenseRecords();

export const alerts: Alert[] = [
  {
    id: "alt-001",
    severity: "critical",
    title: "DEA registration expired — Paws & Claws Veterinary",
    detail: "FB2345678 expired 106 days ago. Controlled substance dispensing must halt until renewed.",
    clinicId: "cln-002",
    createdAt: "2026-03-14",
    category: "dea",
  },
  {
    id: "alt-002",
    severity: "critical",
    title: "DEA registration expired — Midwest Animal Care",
    detail: "FG7890123 expired 32 days ago. Escalated to regional ops.",
    clinicId: "cln-007",
    createdAt: "2026-03-12",
    category: "dea",
  },
  {
    id: "alt-003",
    severity: "warning",
    title: "DEA renewal due in 14 days — Northside Animal Hospital",
    detail: "FA1234567 renewal application not yet submitted.",
    clinicId: "cln-001",
    createdAt: "2026-03-15",
    category: "dea",
  },
  {
    id: "alt-004",
    severity: "warning",
    title: "State license renewal due — Valley Veterinary Group",
    detail: "California DVM facility license expires in 18 days.",
    clinicId: "cln-008",
    createdAt: "2026-03-15",
    category: "license",
  },
  {
    id: "alt-005",
    severity: "warning",
    title: "Acquisition diligence: 2 expired DEAs found",
    detail: "Blue Ridge Veterinary diligence flagged critical compliance gaps.",
    createdAt: "2026-03-10",
    category: "acquisition",
  },
  {
    id: "alt-006",
    severity: "info",
    title: "New acquisition onboarding started",
    detail: "Sunrise Veterinary Clinic (AZ) added to integration queue.",
    clinicId: "cln-004",
    createdAt: "2026-03-08",
    category: "acquisition",
  },
  {
    id: "alt-007",
    severity: "warning",
    title: "Controlled substance log gap — Paws & Claws",
    detail: "Biennial inventory not on file. Last entry 14 months ago.",
    clinicId: "cln-002",
    createdAt: "2026-03-11",
    category: "cs_log",
  },
];
