import type {
  ApiKey,
  CanonicalEntity,
  MatchCandidate,
  Organization,
  RequestLog,
  ResolveMetrics,
  RosterJob,
} from "./resolve-types";

export const organization: Organization = {
  name: "Demo Vet Partners",
  apiCallsThisWeek: 12400,
  autoMatchRate: 94.2,
  activeJobs: 2,
  pendingReviews: 6,
};

export const metrics: ResolveMetrics = {
  resolveCallsThisWeek: 12400,
  autoMatchRate: 94.2,
  pendingReviews: 6,
  canonicalEntities: 1842,
  avgConfidence: 0.91,
};

export const rosterJobs: RosterJob[] = [
  {
    id: "job-sunset",
    name: "Sunset Vet Group acquisition",
    source: "deal_room_export.csv",
    status: "completed",
    totalRecords: 847,
    resolvedRecords: 771,
    reviewCount: 76,
    createdAt: "2026-06-20T14:32:00Z",
    completedAt: "2026-06-20T14:38:00Z",
  },
  {
    id: "job-q1",
    name: "Q1 provider onboarding",
    source: "hr_roster_q1.csv",
    status: "completed",
    totalRecords: 214,
    resolvedRecords: 210,
    reviewCount: 4,
    createdAt: "2026-06-18T09:15:00Z",
    completedAt: "2026-06-18T09:17:00Z",
  },
  {
    id: "job-heritage",
    name: "Heritage Animal Clinics",
    source: "seller_roster_v2.xlsx",
    status: "processing",
    totalRecords: 312,
    resolvedRecords: 198,
    reviewCount: 22,
    createdAt: "2026-06-26T11:00:00Z",
  },
];

export const reviewQueue: MatchCandidate[] = [
  {
    id: "rev-001",
    sourceLabel: "Dr J. Smith",
    sourceDetail: "Sunrise Animal Hospital · Denver, CO",
    targetLabel: "Jonathan Smith, DVM",
    targetDetail: "DEA AB1234567 · CO license VET-88421",
    confidence: 0.62,
    entityType: "provider",
    rosterJobId: "job-sunset",
    rosterJobName: "Sunset Vet Group acquisition",
    fieldScores: [
      { field: "name", score: 0.88, note: "Initial vs full name" },
      { field: "clinic", score: 0.71, note: "Hospital vs Clinic variant" },
      { field: "dea", score: 1.0, note: "Exact match on AB1234567" },
      { field: "state", score: 1.0 },
    ],
    decision: "pending",
  },
  {
    id: "rev-002",
    sourceLabel: "Sunrise Animal Hosp",
    sourceDetail: "1420 E Colfax Ave · Denver, CO",
    targetLabel: "Sunrise Veterinary Clinic",
    targetDetail: "Clinic DEA FD4567890 · 3 linked providers",
    confidence: 0.58,
    entityType: "clinic",
    rosterJobId: "job-sunset",
    rosterJobName: "Sunset Vet Group acquisition",
    fieldScores: [
      { field: "name", score: 0.76 },
      { field: "address", score: 0.82 },
      { field: "dea", score: 0.45, note: "Individual vs clinic registrant" },
      { field: "state", score: 1.0 },
    ],
    decision: "pending",
  },
  {
    id: "rev-003",
    sourceLabel: "M. Chen",
    sourceDetail: "Paws & Claws · Austin, TX",
    targetLabel: "Maria Chen, DVM",
    targetDetail: "DEA BC9876543 · TX license VET-12044",
    confidence: 0.67,
    entityType: "provider",
    rosterJobId: "job-sunset",
    rosterJobName: "Sunset Vet Group acquisition",
    fieldScores: [
      { field: "name", score: 0.79 },
      { field: "clinic", score: 0.91 },
      { field: "license", score: 1.0 },
      { field: "state", score: 1.0 },
    ],
    decision: "pending",
  },
  {
    id: "rev-004",
    sourceLabel: "Heritage AH #4",
    sourceDetail: "Nashville, TN · no DEA on file",
    targetLabel: "Heritage Animal Clinic",
    targetDetail: "DEA FE5678901 · Nashville, TN",
    confidence: 0.55,
    entityType: "clinic",
    rosterJobId: "job-heritage",
    rosterJobName: "Heritage Animal Clinics",
    fieldScores: [
      { field: "name", score: 0.84 },
      { field: "address", score: 0.52, note: "Abbreviated clinic name" },
      { field: "dea", score: 0.0, note: "Missing in source row" },
      { field: "state", score: 1.0 },
    ],
    decision: "pending",
  },
  {
    id: "rev-005",
    sourceLabel: "Dr. Williams",
    sourceDetail: "Coastal Pet Hospital · Tampa, FL",
    targetLabel: "Williamson, Robert DVM",
    targetDetail: "FL license VET-99201 · no DEA match",
    confidence: 0.48,
    entityType: "provider",
    rosterJobId: "job-heritage",
    rosterJobName: "Heritage Animal Clinics",
    fieldScores: [
      { field: "name", score: 0.41, note: "Possible different provider" },
      { field: "clinic", score: 0.95 },
      { field: "license", score: 0.38 },
      { field: "state", score: 1.0 },
    ],
    decision: "pending",
  },
  {
    id: "rev-006",
    sourceLabel: "Lakeview Pet Care",
    sourceDetail: "Chicago, IL · seller spreadsheet row 44",
    targetLabel: "Lakeview Pet Care Center",
    targetDetail: "DEA FC3456789 · 2 providers linked",
    confidence: 0.71,
    entityType: "clinic",
    rosterJobId: "job-q1",
    rosterJobName: "Q1 provider onboarding",
    fieldScores: [
      { field: "name", score: 0.93 },
      { field: "address", score: 0.68, note: "City only in source" },
      { field: "dea", score: 0.88 },
      { field: "state", score: 1.0 },
    ],
    decision: "pending",
  },
];

export const canonicalEntities: CanonicalEntity[] = [
  {
    id: "ent-prov-001",
    type: "provider",
    displayName: "Jonathan Smith, DVM",
    subtitle: "CO license VET-88421 · DEA AB1234567",
    state: "CO",
    deaNumber: "AB1234567",
    licenseNumber: "VET-88421",
    acquisitionSource: "Sunset Vet Group",
    linkedEntityIds: ["ent-clinic-001"],
    lastResolvedAt: "2026-06-20T14:35:00Z",
    confidence: 0.97,
  },
  {
    id: "ent-clinic-001",
    type: "clinic",
    displayName: "Sunrise Veterinary Clinic",
    subtitle: "Denver, CO · Clinic DEA FD4567890",
    state: "CO",
    deaNumber: "FD4567890",
    acquisitionSource: "Sunset Vet Group",
    linkedEntityIds: ["ent-prov-001", "ent-prov-002"],
    lastResolvedAt: "2026-06-20T14:35:00Z",
    confidence: 0.94,
  },
  {
    id: "ent-prov-002",
    type: "provider",
    displayName: "Maria Chen, DVM",
    subtitle: "TX license VET-12044 · DEA BC9876543",
    state: "TX",
    deaNumber: "BC9876543",
    licenseNumber: "VET-12044",
    acquisitionSource: "Sunset Vet Group",
    linkedEntityIds: ["ent-clinic-002"],
    lastResolvedAt: "2026-06-20T14:36:00Z",
    confidence: 0.96,
  },
  {
    id: "ent-clinic-002",
    type: "clinic",
    displayName: "Paws & Claws Veterinary",
    subtitle: "Austin, TX · 4 providers",
    state: "TX",
    acquisitionSource: "Sunset Vet Group",
    linkedEntityIds: ["ent-prov-002"],
    lastResolvedAt: "2026-06-20T14:36:00Z",
    confidence: 0.92,
  },
  {
    id: "ent-clinic-003",
    type: "clinic",
    displayName: "Lakeview Pet Care Center",
    subtitle: "Chicago, IL · DEA FC3456789",
    state: "IL",
    deaNumber: "FC3456789",
    linkedEntityIds: [],
    lastResolvedAt: "2026-06-18T09:16:00Z",
    confidence: 0.98,
  },
  {
    id: "ent-clinic-004",
    type: "clinic",
    displayName: "Heritage Animal Clinic",
    subtitle: "Nashville, TN · DEA FE5678901",
    state: "TN",
    deaNumber: "FE5678901",
    acquisitionSource: "Heritage Animal Clinics",
    linkedEntityIds: [],
    lastResolvedAt: "2026-06-26T11:04:00Z",
    confidence: 0.89,
  },
];

export const apiKeys: ApiKey[] = [
  {
    id: "key-1",
    name: "Production",
    prefix: "vc_live_8f2a",
    createdAt: "2026-03-01T10:00:00Z",
    lastUsedAt: "2026-06-26T10:58:00Z",
  },
  {
    id: "key-2",
    name: "M&A integration sandbox",
    prefix: "vc_test_4b1c",
    createdAt: "2026-05-12T14:00:00Z",
    lastUsedAt: "2026-06-25T16:22:00Z",
  },
];

export const requestLogs: RequestLog[] = [
  {
    id: "log-1",
    tool: "resolve_provider",
    method: "MCP",
    status: 200,
    durationMs: 142,
    timestamp: "2026-06-26T10:58:12Z",
    requestId: "req_8k2m9x",
  },
  {
    id: "log-2",
    tool: "resolve_roster",
    method: "POST",
    status: 202,
    durationMs: 1840,
    timestamp: "2026-06-26T11:00:03Z",
    requestId: "req_7j1n4p",
  },
  {
    id: "log-3",
    tool: "explain_match",
    method: "MCP",
    status: 200,
    durationMs: 89,
    timestamp: "2026-06-26T10:57:44Z",
    requestId: "req_6h0m2q",
  },
  {
    id: "log-4",
    tool: "resolve_clinic",
    method: "POST",
    status: 200,
    durationMs: 156,
    timestamp: "2026-06-26T10:55:01Z",
    requestId: "req_5g9l1r",
  },
  {
    id: "log-5",
    tool: "link_acquisition_entities",
    method: "MCP",
    status: 200,
    durationMs: 312,
    timestamp: "2026-06-26T10:52:30Z",
    requestId: "req_4f8k0s",
  },
  {
    id: "log-6",
    tool: "resolve_provider",
    method: "POST",
    status: 422,
    durationMs: 98,
    timestamp: "2026-06-26T10:48:17Z",
    requestId: "req_3e7j9t",
  },
];

export const mcpTools = [
  {
    name: "resolve_provider",
    description: "Match a messy provider record to a canonical regulatory identity",
  },
  {
    name: "resolve_clinic",
    description: "Match a clinic/location record to a canonical DEA registrant",
  },
  {
    name: "resolve_roster",
    description: "Bulk-resolve an acquisition or onboarding roster",
  },
  {
    name: "explain_match",
    description: "Field-level similarity breakdown for a match candidate",
  },
  {
    name: "link_acquisition_entities",
    description: "Map seller roster entities to buyer portfolio graph",
  },
  {
    name: "get_entity",
    description: "Fetch a canonical provider or clinic by ID",
  },
];
