import type {
  ApiRequestLog,
  CatalogJob,
  DriftAlert,
  Metrics,
  Organization,
  SkuRecord,
} from "./types";

export const organization: Organization = {
  name: "Apex Pick Robotics",
  robotModel: "Apex-Arm V3",
  sitesLive: 7,
  skusScoredThisWeek: 4812,
  pendingReviews: 18,
};

export const metrics: Metrics = {
  skusScoredThisWeek: 4812,
  inEnvelopeRate: 93.4,
  pendingReviews: 18,
  catalogsScored: 14,
  avgConfidence: 0.91,
  predictedFails: 99,
};

export const catalogJobs: CatalogJob[] = [
  {
    id: "job_01",
    name: "Stord — Dallas DC catalog",
    customer: "Stord",
    site: "Dallas DC",
    status: "completed",
    totalSkus: 4820,
    scoredSkus: 4820,
    passCount: 4501,
    marginalCount: 220,
    failCount: 99,
    createdAt: "2026-07-18T14:22:00Z",
  },
  {
    id: "job_02",
    name: "ShipBob — LA inbound SKUs",
    customer: "ShipBob",
    site: "Los Angeles",
    status: "processing",
    totalSkus: 2104,
    scoredSkus: 1540,
    passCount: 1388,
    marginalCount: 112,
    failCount: 40,
    createdAt: "2026-07-19T09:10:00Z",
  },
  {
    id: "job_03",
    name: "Peak season delta — Q4 adds",
    customer: "Internal",
    site: "All sites",
    status: "queued",
    totalSkus: 860,
    scoredSkus: 0,
    passCount: 0,
    marginalCount: 0,
    failCount: 0,
    createdAt: "2026-07-20T08:00:00Z",
  },
  {
    id: "job_04",
    name: "CEVA — Newark pilot catalog",
    customer: "CEVA",
    site: "Newark",
    status: "completed",
    totalSkus: 1250,
    scoredSkus: 1250,
    passCount: 1180,
    marginalCount: 48,
    failCount: 22,
    createdAt: "2026-07-16T11:40:00Z",
  },
];

export const skus: SkuRecord[] = [
  {
    id: "sku_01",
    sku: "ST-8821",
    name: "Silicone spatula set (3-pack)",
    category: "Kitchen",
    packaging: "Poly bag + cardboard hang",
    dimensions: "28 × 8 × 3 cm",
    weightG: 240,
    verdict: "fail",
    predictedPickRate: 0.61,
    confidence: 0.94,
    failureMode: "deformable",
    mitigation: "Route to soft-gripper cell or exception pack lane",
    catalogId: "job_01",
  },
  {
    id: "sku_02",
    sku: "ST-4410",
    name: "Mirror compact (chrome)",
    category: "Beauty",
    packaging: "Shrink wrap",
    dimensions: "9 × 9 × 2 cm",
    weightG: 85,
    verdict: "fail",
    predictedPickRate: 0.54,
    confidence: 0.89,
    failureMode: "reflective",
    mitigation: "Add matte sleeve or force vision model for chrome SKUs",
    catalogId: "job_01",
  },
  {
    id: "sku_03",
    sku: "ST-1099",
    name: "Protein bar variety box",
    category: "CPG",
    packaging: "Corrugated case",
    dimensions: "32 × 22 × 12 cm",
    weightG: 1800,
    verdict: "pass",
    predictedPickRate: 0.98,
    confidence: 0.97,
    catalogId: "job_01",
  },
  {
    id: "sku_04",
    sku: "ST-2204",
    name: "Yoga mat (rolled)",
    category: "Fitness",
    packaging: "Shrink wrap",
    dimensions: "65 × 14 × 14 cm",
    weightG: 1200,
    verdict: "marginal",
    predictedPickRate: 0.82,
    confidence: 0.86,
    failureMode: "grasp_slip",
    mitigation: "Increase gripper force profile; slot upright",
    catalogId: "job_01",
  },
  {
    id: "sku_05",
    sku: "SB-7712",
    name: "LED string lights 50ft",
    category: "Home",
    packaging: "Poly bag",
    dimensions: "22 × 15 × 4 cm",
    weightG: 310,
    verdict: "marginal",
    predictedPickRate: 0.79,
    confidence: 0.88,
    failureMode: "vision_miss",
    mitigation: "Add tote divider; lower pick height",
    catalogId: "job_02",
  },
  {
    id: "sku_06",
    sku: "SB-3301",
    name: "Ceramic mug set (4)",
    category: "Kitchen",
    packaging: "Inner carton",
    dimensions: "30 × 24 × 14 cm",
    weightG: 2100,
    verdict: "pass",
    predictedPickRate: 0.96,
    confidence: 0.95,
    catalogId: "job_02",
  },
  {
    id: "sku_07",
    sku: "ST-5508",
    name: "Wireless earbuds case",
    category: "Electronics",
    packaging: "Clamshell blister",
    dimensions: "12 × 8 × 4 cm",
    weightG: 95,
    verdict: "fail",
    predictedPickRate: 0.58,
    confidence: 0.91,
    failureMode: "reflective",
    mitigation: "Desleeve before robot cell or use vacuum cup",
    catalogId: "job_01",
  },
  {
    id: "sku_08",
    sku: "CV-9012",
    name: "Office paper ream",
    category: "Office",
    packaging: "Paper wrap",
    dimensions: "28 × 22 × 6 cm",
    weightG: 2500,
    verdict: "pass",
    predictedPickRate: 0.99,
    confidence: 0.98,
    catalogId: "job_04",
  },
  {
    id: "sku_09",
    sku: "ST-6670",
    name: "Fleece throw blanket",
    category: "Home",
    packaging: "Vacuum poly bag",
    dimensions: "40 × 30 × 8 cm",
    weightG: 900,
    verdict: "marginal",
    predictedPickRate: 0.84,
    confidence: 0.83,
    failureMode: "deformable",
    mitigation: "Compress further or use two-finger pinch sequence",
    catalogId: "job_01",
  },
  {
    id: "sku_10",
    sku: "ST-1188",
    name: "Vitamin bottle 120ct",
    category: "Health",
    packaging: "Rigid bottle",
    dimensions: "8 × 8 × 16 cm",
    weightG: 280,
    verdict: "pass",
    predictedPickRate: 0.97,
    confidence: 0.96,
    catalogId: "job_01",
  },
  {
    id: "sku_11",
    sku: "SB-4420",
    name: "Phone screen protector kit",
    category: "Electronics",
    packaging: "Thin retail card",
    dimensions: "18 × 12 × 0.4 cm",
    weightG: 45,
    verdict: "fail",
    predictedPickRate: 0.49,
    confidence: 0.93,
    failureMode: "size_out_of_range",
    mitigation: "Exception lane — too thin for current end-effector",
    catalogId: "job_02",
  },
  {
    id: "sku_12",
    sku: "ST-8044",
    name: "Laundry detergent pods (42)",
    category: "CPG",
    packaging: "Stand-up pouch",
    dimensions: "24 × 18 × 10 cm",
    weightG: 720,
    verdict: "pass",
    predictedPickRate: 0.94,
    confidence: 0.9,
    catalogId: "job_01",
  },
];

export const driftAlerts: DriftAlert[] = [
  {
    id: "drift_01",
    site: "Dallas DC",
    signal: "Packaging mix shift",
    severity: "warning",
    detail: "Poly-bag SKU share up 18% vs envelope baseline this week",
    detectedAt: "2026-07-19T16:40:00Z",
  },
  {
    id: "drift_02",
    site: "Los Angeles",
    signal: "Peak throughput",
    severity: "critical",
    detail: "Orders/hour at 1.4× training envelope — predict 12% pick-rate drop",
    detectedAt: "2026-07-20T06:15:00Z",
  },
  {
    id: "drift_03",
    site: "Newark",
    signal: "Lighting change",
    severity: "info",
    detail: "Aisle 4 Lux down 22% after fixture swap — vision confidence dipping",
    detectedAt: "2026-07-18T21:05:00Z",
  },
];

export const apiLogs: ApiRequestLog[] = [
  {
    id: "req_1",
    method: "POST",
    path: "/v1/catalogs/score",
    status: 200,
    latencyMs: 842,
    at: "2026-07-20T08:42:11Z",
  },
  {
    id: "req_2",
    method: "GET",
    path: "/v1/skus/ST-8821",
    status: 200,
    latencyMs: 48,
    at: "2026-07-20T08:41:02Z",
  },
  {
    id: "req_3",
    method: "POST",
    path: "/v1/envelope/predict",
    status: 200,
    latencyMs: 312,
    at: "2026-07-20T08:38:55Z",
  },
  {
    id: "req_4",
    method: "GET",
    path: "/v1/alerts",
    status: 200,
    latencyMs: 61,
    at: "2026-07-20T08:30:14Z",
  },
  {
    id: "req_5",
    method: "POST",
    path: "/v1/mitigations/apply",
    status: 201,
    latencyMs: 120,
    at: "2026-07-20T08:22:40Z",
  },
];

export const failureModeLabel: Record<string, string> = {
  grasp_slip: "Grasp slip",
  vision_miss: "Vision miss",
  deformable: "Deformable object",
  reflective: "Reflective surface",
  size_out_of_range: "Size out of range",
  throughput_drop: "Throughput drop",
};
